/*
 * generated by Xtext 2.25.0
 */
package nl.esi.comma.expressions.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ExpressionsAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("nl/esi/comma/expressions/parser/antlr/internal/InternalExpressions.tokens");
	}
}
