/*
 * generated by Xtext 2.25.0
 */
package nl.esi.comma.expressions.ide;


/**
 * Use this class to register ide components.
 */
public class ExpressionsIdeModule extends AbstractExpressionsIdeModule {
}
