/**
 * generated by Xtext 2.25.0
 */
package nl.esi.comma.behavior.scl.scl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>At Most</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.esi.comma.behavior.scl.scl.AtMost#getRef <em>Ref</em>}</li>
 *   <li>{@link nl.esi.comma.behavior.scl.scl.AtMost#getNum <em>Num</em>}</li>
 * </ul>
 *
 * @see nl.esi.comma.behavior.scl.scl.SclPackage#getAtMost()
 * @model
 * @generated
 */
public interface AtMost extends EObject
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' containment reference list.
   * The list contents are of type {@link nl.esi.comma.behavior.scl.scl.Ref}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' containment reference list.
   * @see nl.esi.comma.behavior.scl.scl.SclPackage#getAtMost_Ref()
   * @model containment="true"
   * @generated
   */
  EList<Ref> getRef();

  /**
   * Returns the value of the '<em><b>Num</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Num</em>' attribute.
   * @see #setNum(int)
   * @see nl.esi.comma.behavior.scl.scl.SclPackage#getAtMost_Num()
   * @model
   * @generated
   */
  int getNum();

  /**
   * Sets the value of the '{@link nl.esi.comma.behavior.scl.scl.AtMost#getNum <em>Num</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Num</em>' attribute.
   * @see #getNum()
   * @generated
   */
  void setNum(int value);

} // AtMost
