/**
 * generated by Xtext 2.25.0
 */
package nl.esi.comma.behavior.scl.scl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ref Sequence</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.esi.comma.behavior.scl.scl.RefSequence#getSeq <em>Seq</em>}</li>
 * </ul>
 *
 * @see nl.esi.comma.behavior.scl.scl.SclPackage#getRefSequence()
 * @model
 * @generated
 */
public interface RefSequence extends Ref
{
  /**
   * Returns the value of the '<em><b>Seq</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Seq</em>' reference.
   * @see #setSeq(SequenceDef)
   * @see nl.esi.comma.behavior.scl.scl.SclPackage#getRefSequence_Seq()
   * @model
   * @generated
   */
  SequenceDef getSeq();

  /**
   * Sets the value of the '{@link nl.esi.comma.behavior.scl.scl.RefSequence#getSeq <em>Seq</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Seq</em>' reference.
   * @see #getSeq()
   * @generated
   */
  void setSeq(SequenceDef value);

} // RefSequence
