/**
 * generated by Xtext 2.25.0
 */
package nl.esi.comma.behavior.scl.scl.impl;

import java.util.Collection;

import nl.esi.comma.behavior.scl.scl.ExclusiveChoice;
import nl.esi.comma.behavior.scl.scl.Ref;
import nl.esi.comma.behavior.scl.scl.SclPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Exclusive Choice</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link nl.esi.comma.behavior.scl.scl.impl.ExclusiveChoiceImpl#isEitherA <em>Either A</em>}</li>
 *   <li>{@link nl.esi.comma.behavior.scl.scl.impl.ExclusiveChoiceImpl#getRefA <em>Ref A</em>}</li>
 *   <li>{@link nl.esi.comma.behavior.scl.scl.impl.ExclusiveChoiceImpl#isEitherB <em>Either B</em>}</li>
 *   <li>{@link nl.esi.comma.behavior.scl.scl.impl.ExclusiveChoiceImpl#getRefB <em>Ref B</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ExclusiveChoiceImpl extends MinimalEObjectImpl.Container implements ExclusiveChoice
{
  /**
   * The default value of the '{@link #isEitherA() <em>Either A</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isEitherA()
   * @generated
   * @ordered
   */
  protected static final boolean EITHER_A_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isEitherA() <em>Either A</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isEitherA()
   * @generated
   * @ordered
   */
  protected boolean eitherA = EITHER_A_EDEFAULT;

  /**
   * The cached value of the '{@link #getRefA() <em>Ref A</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRefA()
   * @generated
   * @ordered
   */
  protected EList<Ref> refA;

  /**
   * The default value of the '{@link #isEitherB() <em>Either B</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isEitherB()
   * @generated
   * @ordered
   */
  protected static final boolean EITHER_B_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isEitherB() <em>Either B</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isEitherB()
   * @generated
   * @ordered
   */
  protected boolean eitherB = EITHER_B_EDEFAULT;

  /**
   * The cached value of the '{@link #getRefB() <em>Ref B</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRefB()
   * @generated
   * @ordered
   */
  protected EList<Ref> refB;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExclusiveChoiceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SclPackage.Literals.EXCLUSIVE_CHOICE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isEitherA()
  {
    return eitherA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEitherA(boolean newEitherA)
  {
    boolean oldEitherA = eitherA;
    eitherA = newEitherA;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SclPackage.EXCLUSIVE_CHOICE__EITHER_A, oldEitherA, eitherA));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Ref> getRefA()
  {
    if (refA == null)
    {
      refA = new EObjectContainmentEList<Ref>(Ref.class, this, SclPackage.EXCLUSIVE_CHOICE__REF_A);
    }
    return refA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isEitherB()
  {
    return eitherB;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEitherB(boolean newEitherB)
  {
    boolean oldEitherB = eitherB;
    eitherB = newEitherB;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SclPackage.EXCLUSIVE_CHOICE__EITHER_B, oldEitherB, eitherB));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Ref> getRefB()
  {
    if (refB == null)
    {
      refB = new EObjectContainmentEList<Ref>(Ref.class, this, SclPackage.EXCLUSIVE_CHOICE__REF_B);
    }
    return refB;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SclPackage.EXCLUSIVE_CHOICE__REF_A:
        return ((InternalEList<?>)getRefA()).basicRemove(otherEnd, msgs);
      case SclPackage.EXCLUSIVE_CHOICE__REF_B:
        return ((InternalEList<?>)getRefB()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SclPackage.EXCLUSIVE_CHOICE__EITHER_A:
        return isEitherA();
      case SclPackage.EXCLUSIVE_CHOICE__REF_A:
        return getRefA();
      case SclPackage.EXCLUSIVE_CHOICE__EITHER_B:
        return isEitherB();
      case SclPackage.EXCLUSIVE_CHOICE__REF_B:
        return getRefB();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SclPackage.EXCLUSIVE_CHOICE__EITHER_A:
        setEitherA((Boolean)newValue);
        return;
      case SclPackage.EXCLUSIVE_CHOICE__REF_A:
        getRefA().clear();
        getRefA().addAll((Collection<? extends Ref>)newValue);
        return;
      case SclPackage.EXCLUSIVE_CHOICE__EITHER_B:
        setEitherB((Boolean)newValue);
        return;
      case SclPackage.EXCLUSIVE_CHOICE__REF_B:
        getRefB().clear();
        getRefB().addAll((Collection<? extends Ref>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SclPackage.EXCLUSIVE_CHOICE__EITHER_A:
        setEitherA(EITHER_A_EDEFAULT);
        return;
      case SclPackage.EXCLUSIVE_CHOICE__REF_A:
        getRefA().clear();
        return;
      case SclPackage.EXCLUSIVE_CHOICE__EITHER_B:
        setEitherB(EITHER_B_EDEFAULT);
        return;
      case SclPackage.EXCLUSIVE_CHOICE__REF_B:
        getRefB().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SclPackage.EXCLUSIVE_CHOICE__EITHER_A:
        return eitherA != EITHER_A_EDEFAULT;
      case SclPackage.EXCLUSIVE_CHOICE__REF_A:
        return refA != null && !refA.isEmpty();
      case SclPackage.EXCLUSIVE_CHOICE__EITHER_B:
        return eitherB != EITHER_B_EDEFAULT;
      case SclPackage.EXCLUSIVE_CHOICE__REF_B:
        return refB != null && !refB.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (eitherA: ");
    result.append(eitherA);
    result.append(", eitherB: ");
    result.append(eitherB);
    result.append(')');
    return result.toString();
  }

} //ExclusiveChoiceImpl
