/**
 * generated by Xtext 2.25.0
 */
package nl.esi.comma.behavior.scl.scl.impl;

import nl.esi.comma.behavior.scl.scl.Action;
import nl.esi.comma.behavior.scl.scl.ActionParam;
import nl.esi.comma.behavior.scl.scl.ActionType;
import nl.esi.comma.behavior.scl.scl.Actions;
import nl.esi.comma.behavior.scl.scl.AlternatePrecedence;
import nl.esi.comma.behavior.scl.scl.AlternateResponse;
import nl.esi.comma.behavior.scl.scl.AlternateSuccession;
import nl.esi.comma.behavior.scl.scl.AtLeast;
import nl.esi.comma.behavior.scl.scl.AtMost;
import nl.esi.comma.behavior.scl.scl.ChainPrecedence;
import nl.esi.comma.behavior.scl.scl.ChainResponse;
import nl.esi.comma.behavior.scl.scl.ChainSuccession;
import nl.esi.comma.behavior.scl.scl.Choice;
import nl.esi.comma.behavior.scl.scl.CoExistance;
import nl.esi.comma.behavior.scl.scl.Composition;
import nl.esi.comma.behavior.scl.scl.Dependencies;
import nl.esi.comma.behavior.scl.scl.End;
import nl.esi.comma.behavior.scl.scl.Exact;
import nl.esi.comma.behavior.scl.scl.ExclusiveChoice;
import nl.esi.comma.behavior.scl.scl.Existential;
import nl.esi.comma.behavior.scl.scl.Feature;
import nl.esi.comma.behavior.scl.scl.Features;
import nl.esi.comma.behavior.scl.scl.Future;
import nl.esi.comma.behavior.scl.scl.Init;
import nl.esi.comma.behavior.scl.scl.Model;
import nl.esi.comma.behavior.scl.scl.NotChainSuccession;
import nl.esi.comma.behavior.scl.scl.NotCoExistance;
import nl.esi.comma.behavior.scl.scl.NotSuccession;
import nl.esi.comma.behavior.scl.scl.ParamAct;
import nl.esi.comma.behavior.scl.scl.Past;
import nl.esi.comma.behavior.scl.scl.Precedence;
import nl.esi.comma.behavior.scl.scl.Ref;
import nl.esi.comma.behavior.scl.scl.RefSequence;
import nl.esi.comma.behavior.scl.scl.RefStep;
import nl.esi.comma.behavior.scl.scl.RespondedExistence;
import nl.esi.comma.behavior.scl.scl.Response;
import nl.esi.comma.behavior.scl.scl.SclFactory;
import nl.esi.comma.behavior.scl.scl.SclPackage;
import nl.esi.comma.behavior.scl.scl.SequenceDef;
import nl.esi.comma.behavior.scl.scl.SimpleChoice;
import nl.esi.comma.behavior.scl.scl.Succession;
import nl.esi.comma.behavior.scl.scl.Templates;

import nl.esi.comma.expressions.expressions.ExpressionsPackage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class SclPackageImpl extends EPackageImpl implements SclPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass compositionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass sequenceDefEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass paramActEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass refEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass refStepEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass refSequenceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass featuresEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass featureEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass actionsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass actionParamEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass actionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass templatesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass pastEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass futureEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dependenciesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass choiceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass existentialEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass exclusiveChoiceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass simpleChoiceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass notChainSuccessionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass notCoExistanceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass notSuccessionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass chainSuccessionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass alternateSuccessionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass successionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass coExistanceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass respondedExistenceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass chainPrecedenceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass chainResponseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass alternateResponseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass alternatePrecedenceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass responseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass precedenceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass endEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass initEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass atMostEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass exactEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass atLeastEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum actionTypeEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see nl.esi.comma.behavior.scl.scl.SclPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private SclPackageImpl()
  {
    super(eNS_URI, SclFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link SclPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static SclPackage init()
  {
    if (isInited) return (SclPackage)EPackage.Registry.INSTANCE.getEPackage(SclPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredSclPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    SclPackageImpl theSclPackage = registeredSclPackage instanceof SclPackageImpl ? (SclPackageImpl)registeredSclPackage : new SclPackageImpl();

    isInited = true;

    // Initialize simple dependencies
    ExpressionsPackage.eINSTANCE.eClass();

    // Create package meta-data objects
    theSclPackage.createPackageContents();

    // Initialize created meta-data
    theSclPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theSclPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(SclPackage.eNS_URI, theSclPackage);
    return theSclPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_Features()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_Actions()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_Sequences()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_Composition()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_CommonFeatures()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_Templates()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getModel_UseLabels()
  {
    return (EAttribute)modelEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getComposition()
  {
    return compositionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getComposition_Name()
  {
    return (EAttribute)compositionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComposition_Templates()
  {
    return (EReference)compositionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getComposition_DescTxt()
  {
    return (EAttribute)compositionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComposition_CommonFeatures()
  {
    return (EReference)compositionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getComposition_TagStr()
  {
    return (EAttribute)compositionEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSequenceDef()
  {
    return sequenceDefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSequenceDef_Name()
  {
    return (EAttribute)sequenceDefEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSequenceDef_ActList()
  {
    return (EReference)sequenceDefEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getParamAct()
  {
    return paramActEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getParamAct_Act()
  {
    return (EReference)paramActEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getParamAct_Idx()
  {
    return (EAttribute)paramActEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRef()
  {
    return refEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRefStep()
  {
    return refStepEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRefStep_Step()
  {
    return (EReference)refStepEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRefStep_Idx()
  {
    return (EAttribute)refStepEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRefSequence()
  {
    return refSequenceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRefSequence_Seq()
  {
    return (EReference)refSequenceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFeatures()
  {
    return featuresEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFeatures_Feature()
  {
    return (EReference)featuresEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFeature()
  {
    return featureEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getFeature_Name()
  {
    return (EAttribute)featureEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getActions()
  {
    return actionsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getActions_Act()
  {
    return (EReference)actionsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getActionParam()
  {
    return actionParamEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getActionParam_Parameters()
  {
    return (EReference)actionParamEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAction()
  {
    return actionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAction_Act()
  {
    return (EAttribute)actionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAction_Name()
  {
    return (EAttribute)actionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAction_Label()
  {
    return (EAttribute)actionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAction_ActParam()
  {
    return (EReference)actionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTemplates()
  {
    return templatesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTemplates_Name()
  {
    return (EAttribute)templatesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTemplates_Type()
  {
    return (EReference)templatesEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTemplates_Features()
  {
    return (EReference)templatesEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPast()
  {
    return pastEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPast_Type()
  {
    return (EReference)pastEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFuture()
  {
    return futureEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFuture_Type()
  {
    return (EReference)futureEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDependencies()
  {
    return dependenciesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDependencies_Type()
  {
    return (EReference)dependenciesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getChoice()
  {
    return choiceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getChoice_Type()
  {
    return (EReference)choiceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExistential()
  {
    return existentialEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getExistential_Type()
  {
    return (EReference)existentialEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExclusiveChoice()
  {
    return exclusiveChoiceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExclusiveChoice_EitherA()
  {
    return (EAttribute)exclusiveChoiceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getExclusiveChoice_RefA()
  {
    return (EReference)exclusiveChoiceEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExclusiveChoice_EitherB()
  {
    return (EAttribute)exclusiveChoiceEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getExclusiveChoice_RefB()
  {
    return (EReference)exclusiveChoiceEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSimpleChoice()
  {
    return simpleChoiceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSimpleChoice_RefA()
  {
    return (EReference)simpleChoiceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getNotChainSuccession()
  {
    return notChainSuccessionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getNotChainSuccession_EitherA()
  {
    return (EAttribute)notChainSuccessionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getNotChainSuccession_RefA()
  {
    return (EReference)notChainSuccessionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getNotChainSuccession_EitherB()
  {
    return (EAttribute)notChainSuccessionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getNotChainSuccession_RefB()
  {
    return (EReference)notChainSuccessionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getNotCoExistance()
  {
    return notCoExistanceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getNotCoExistance_RefA()
  {
    return (EReference)notCoExistanceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getNotSuccession()
  {
    return notSuccessionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getNotSuccession_EitherA()
  {
    return (EAttribute)notSuccessionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getNotSuccession_RefA()
  {
    return (EReference)notSuccessionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getNotSuccession_EitherB()
  {
    return (EAttribute)notSuccessionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getNotSuccession_RefB()
  {
    return (EReference)notSuccessionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getChainSuccession()
  {
    return chainSuccessionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getChainSuccession_EitherA()
  {
    return (EAttribute)chainSuccessionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getChainSuccession_RefA()
  {
    return (EReference)chainSuccessionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getChainSuccession_EitherB()
  {
    return (EAttribute)chainSuccessionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getChainSuccession_RefB()
  {
    return (EReference)chainSuccessionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getChainSuccession_MinVal()
  {
    return (EAttribute)chainSuccessionEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getChainSuccession_MaxVal()
  {
    return (EAttribute)chainSuccessionEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAlternateSuccession()
  {
    return alternateSuccessionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAlternateSuccession_EitherA()
  {
    return (EAttribute)alternateSuccessionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAlternateSuccession_RefA()
  {
    return (EReference)alternateSuccessionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAlternateSuccession_EitherB()
  {
    return (EAttribute)alternateSuccessionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAlternateSuccession_RefB()
  {
    return (EReference)alternateSuccessionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAlternateSuccession_EitherC()
  {
    return (EAttribute)alternateSuccessionEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAlternateSuccession_Negation()
  {
    return (EAttribute)alternateSuccessionEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAlternateSuccession_RefC()
  {
    return (EReference)alternateSuccessionEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSuccession()
  {
    return successionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSuccession_EitherA()
  {
    return (EAttribute)successionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSuccession_RefA()
  {
    return (EReference)successionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSuccession_EitherB()
  {
    return (EAttribute)successionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSuccession_RefB()
  {
    return (EReference)successionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSuccession_MinVal()
  {
    return (EAttribute)successionEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSuccession_MaxVal()
  {
    return (EAttribute)successionEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCoExistance()
  {
    return coExistanceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCoExistance_RefA()
  {
    return (EReference)coExistanceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRespondedExistence()
  {
    return respondedExistenceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRespondedExistence_EitherA()
  {
    return (EAttribute)respondedExistenceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRespondedExistence_RefA()
  {
    return (EReference)respondedExistenceEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRespondedExistence_EitherB()
  {
    return (EAttribute)respondedExistenceEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRespondedExistence_RefB()
  {
    return (EReference)respondedExistenceEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getChainPrecedence()
  {
    return chainPrecedenceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getChainPrecedence_EitherB()
  {
    return (EAttribute)chainPrecedenceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getChainPrecedence_RefB()
  {
    return (EReference)chainPrecedenceEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getChainPrecedence_EitherA()
  {
    return (EAttribute)chainPrecedenceEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getChainPrecedence_RefA()
  {
    return (EReference)chainPrecedenceEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getChainPrecedence_Not()
  {
    return (EAttribute)chainPrecedenceEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getChainPrecedence_MinVal()
  {
    return (EAttribute)chainPrecedenceEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getChainPrecedence_MaxVal()
  {
    return (EAttribute)chainPrecedenceEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getChainResponse()
  {
    return chainResponseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getChainResponse_EitherA()
  {
    return (EAttribute)chainResponseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getChainResponse_RefA()
  {
    return (EReference)chainResponseEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getChainResponse_EitherB()
  {
    return (EAttribute)chainResponseEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getChainResponse_RefB()
  {
    return (EReference)chainResponseEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getChainResponse_Not()
  {
    return (EAttribute)chainResponseEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getChainResponse_MinVal()
  {
    return (EAttribute)chainResponseEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getChainResponse_MaxVal()
  {
    return (EAttribute)chainResponseEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAlternateResponse()
  {
    return alternateResponseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAlternateResponse_EitherA()
  {
    return (EAttribute)alternateResponseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAlternateResponse_RefA()
  {
    return (EReference)alternateResponseEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAlternateResponse_EitherB()
  {
    return (EAttribute)alternateResponseEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAlternateResponse_RefB()
  {
    return (EReference)alternateResponseEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAlternateResponse_MinVal()
  {
    return (EAttribute)alternateResponseEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAlternateResponse_MaxVal()
  {
    return (EAttribute)alternateResponseEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAlternateResponse_Not()
  {
    return (EAttribute)alternateResponseEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAlternateResponse_EitherC()
  {
    return (EAttribute)alternateResponseEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAlternateResponse_RefC()
  {
    return (EReference)alternateResponseEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAlternatePrecedence()
  {
    return alternatePrecedenceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAlternatePrecedence_EitherB()
  {
    return (EAttribute)alternatePrecedenceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAlternatePrecedence_RefB()
  {
    return (EReference)alternatePrecedenceEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAlternatePrecedence_EitherA()
  {
    return (EAttribute)alternatePrecedenceEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAlternatePrecedence_RefA()
  {
    return (EReference)alternatePrecedenceEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAlternatePrecedence_MinVal()
  {
    return (EAttribute)alternatePrecedenceEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAlternatePrecedence_MaxVal()
  {
    return (EAttribute)alternatePrecedenceEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAlternatePrecedence_Not()
  {
    return (EAttribute)alternatePrecedenceEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAlternatePrecedence_EitherC()
  {
    return (EAttribute)alternatePrecedenceEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAlternatePrecedence_RefC()
  {
    return (EReference)alternatePrecedenceEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getResponse()
  {
    return responseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getResponse_EitherA()
  {
    return (EAttribute)responseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getResponse_RefA()
  {
    return (EReference)responseEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getResponse_EitherB()
  {
    return (EAttribute)responseEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getResponse_RefB()
  {
    return (EReference)responseEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getResponse_Not()
  {
    return (EAttribute)responseEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getResponse_MinVal()
  {
    return (EAttribute)responseEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getResponse_MaxVal()
  {
    return (EAttribute)responseEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPrecedence()
  {
    return precedenceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPrecedence_EitherB()
  {
    return (EAttribute)precedenceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPrecedence_RefB()
  {
    return (EReference)precedenceEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPrecedence_EitherA()
  {
    return (EAttribute)precedenceEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPrecedence_RefA()
  {
    return (EReference)precedenceEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPrecedence_Not()
  {
    return (EAttribute)precedenceEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPrecedence_MinVal()
  {
    return (EAttribute)precedenceEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPrecedence_MaxVal()
  {
    return (EAttribute)precedenceEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEnd()
  {
    return endEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEnd_Ref()
  {
    return (EReference)endEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInit()
  {
    return initEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getInit_Ref()
  {
    return (EReference)initEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAtMost()
  {
    return atMostEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAtMost_Ref()
  {
    return (EReference)atMostEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAtMost_Num()
  {
    return (EAttribute)atMostEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExact()
  {
    return exactEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getExact_Ref()
  {
    return (EReference)exactEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExact_Num()
  {
    return (EAttribute)exactEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExact_Consecutively()
  {
    return (EAttribute)exactEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExact_MinVal()
  {
    return (EAttribute)exactEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExact_MaxVal()
  {
    return (EAttribute)exactEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAtLeast()
  {
    return atLeastEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAtLeast_Ref()
  {
    return (EReference)atLeastEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAtLeast_Num()
  {
    return (EAttribute)atLeastEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAtLeast_MinVal()
  {
    return (EAttribute)atLeastEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAtLeast_MaxVal()
  {
    return (EAttribute)atLeastEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getActionType()
  {
    return actionTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SclFactory getSclFactory()
  {
    return (SclFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    modelEClass = createEClass(MODEL);
    createEReference(modelEClass, MODEL__FEATURES);
    createEReference(modelEClass, MODEL__ACTIONS);
    createEReference(modelEClass, MODEL__SEQUENCES);
    createEReference(modelEClass, MODEL__COMPOSITION);
    createEReference(modelEClass, MODEL__COMMON_FEATURES);
    createEReference(modelEClass, MODEL__TEMPLATES);
    createEAttribute(modelEClass, MODEL__USE_LABELS);

    compositionEClass = createEClass(COMPOSITION);
    createEAttribute(compositionEClass, COMPOSITION__NAME);
    createEReference(compositionEClass, COMPOSITION__TEMPLATES);
    createEAttribute(compositionEClass, COMPOSITION__DESC_TXT);
    createEReference(compositionEClass, COMPOSITION__COMMON_FEATURES);
    createEAttribute(compositionEClass, COMPOSITION__TAG_STR);

    sequenceDefEClass = createEClass(SEQUENCE_DEF);
    createEAttribute(sequenceDefEClass, SEQUENCE_DEF__NAME);
    createEReference(sequenceDefEClass, SEQUENCE_DEF__ACT_LIST);

    paramActEClass = createEClass(PARAM_ACT);
    createEReference(paramActEClass, PARAM_ACT__ACT);
    createEAttribute(paramActEClass, PARAM_ACT__IDX);

    refEClass = createEClass(REF);

    refStepEClass = createEClass(REF_STEP);
    createEReference(refStepEClass, REF_STEP__STEP);
    createEAttribute(refStepEClass, REF_STEP__IDX);

    refSequenceEClass = createEClass(REF_SEQUENCE);
    createEReference(refSequenceEClass, REF_SEQUENCE__SEQ);

    featuresEClass = createEClass(FEATURES);
    createEReference(featuresEClass, FEATURES__FEATURE);

    featureEClass = createEClass(FEATURE);
    createEAttribute(featureEClass, FEATURE__NAME);

    actionsEClass = createEClass(ACTIONS);
    createEReference(actionsEClass, ACTIONS__ACT);

    actionParamEClass = createEClass(ACTION_PARAM);
    createEReference(actionParamEClass, ACTION_PARAM__PARAMETERS);

    actionEClass = createEClass(ACTION);
    createEAttribute(actionEClass, ACTION__ACT);
    createEAttribute(actionEClass, ACTION__NAME);
    createEAttribute(actionEClass, ACTION__LABEL);
    createEReference(actionEClass, ACTION__ACT_PARAM);

    templatesEClass = createEClass(TEMPLATES);
    createEAttribute(templatesEClass, TEMPLATES__NAME);
    createEReference(templatesEClass, TEMPLATES__TYPE);
    createEReference(templatesEClass, TEMPLATES__FEATURES);

    pastEClass = createEClass(PAST);
    createEReference(pastEClass, PAST__TYPE);

    futureEClass = createEClass(FUTURE);
    createEReference(futureEClass, FUTURE__TYPE);

    dependenciesEClass = createEClass(DEPENDENCIES);
    createEReference(dependenciesEClass, DEPENDENCIES__TYPE);

    choiceEClass = createEClass(CHOICE);
    createEReference(choiceEClass, CHOICE__TYPE);

    existentialEClass = createEClass(EXISTENTIAL);
    createEReference(existentialEClass, EXISTENTIAL__TYPE);

    exclusiveChoiceEClass = createEClass(EXCLUSIVE_CHOICE);
    createEAttribute(exclusiveChoiceEClass, EXCLUSIVE_CHOICE__EITHER_A);
    createEReference(exclusiveChoiceEClass, EXCLUSIVE_CHOICE__REF_A);
    createEAttribute(exclusiveChoiceEClass, EXCLUSIVE_CHOICE__EITHER_B);
    createEReference(exclusiveChoiceEClass, EXCLUSIVE_CHOICE__REF_B);

    simpleChoiceEClass = createEClass(SIMPLE_CHOICE);
    createEReference(simpleChoiceEClass, SIMPLE_CHOICE__REF_A);

    notChainSuccessionEClass = createEClass(NOT_CHAIN_SUCCESSION);
    createEAttribute(notChainSuccessionEClass, NOT_CHAIN_SUCCESSION__EITHER_A);
    createEReference(notChainSuccessionEClass, NOT_CHAIN_SUCCESSION__REF_A);
    createEAttribute(notChainSuccessionEClass, NOT_CHAIN_SUCCESSION__EITHER_B);
    createEReference(notChainSuccessionEClass, NOT_CHAIN_SUCCESSION__REF_B);

    notCoExistanceEClass = createEClass(NOT_CO_EXISTANCE);
    createEReference(notCoExistanceEClass, NOT_CO_EXISTANCE__REF_A);

    notSuccessionEClass = createEClass(NOT_SUCCESSION);
    createEAttribute(notSuccessionEClass, NOT_SUCCESSION__EITHER_A);
    createEReference(notSuccessionEClass, NOT_SUCCESSION__REF_A);
    createEAttribute(notSuccessionEClass, NOT_SUCCESSION__EITHER_B);
    createEReference(notSuccessionEClass, NOT_SUCCESSION__REF_B);

    chainSuccessionEClass = createEClass(CHAIN_SUCCESSION);
    createEAttribute(chainSuccessionEClass, CHAIN_SUCCESSION__EITHER_A);
    createEReference(chainSuccessionEClass, CHAIN_SUCCESSION__REF_A);
    createEAttribute(chainSuccessionEClass, CHAIN_SUCCESSION__EITHER_B);
    createEReference(chainSuccessionEClass, CHAIN_SUCCESSION__REF_B);
    createEAttribute(chainSuccessionEClass, CHAIN_SUCCESSION__MIN_VAL);
    createEAttribute(chainSuccessionEClass, CHAIN_SUCCESSION__MAX_VAL);

    alternateSuccessionEClass = createEClass(ALTERNATE_SUCCESSION);
    createEAttribute(alternateSuccessionEClass, ALTERNATE_SUCCESSION__EITHER_A);
    createEReference(alternateSuccessionEClass, ALTERNATE_SUCCESSION__REF_A);
    createEAttribute(alternateSuccessionEClass, ALTERNATE_SUCCESSION__EITHER_B);
    createEReference(alternateSuccessionEClass, ALTERNATE_SUCCESSION__REF_B);
    createEAttribute(alternateSuccessionEClass, ALTERNATE_SUCCESSION__EITHER_C);
    createEAttribute(alternateSuccessionEClass, ALTERNATE_SUCCESSION__NEGATION);
    createEReference(alternateSuccessionEClass, ALTERNATE_SUCCESSION__REF_C);

    successionEClass = createEClass(SUCCESSION);
    createEAttribute(successionEClass, SUCCESSION__EITHER_A);
    createEReference(successionEClass, SUCCESSION__REF_A);
    createEAttribute(successionEClass, SUCCESSION__EITHER_B);
    createEReference(successionEClass, SUCCESSION__REF_B);
    createEAttribute(successionEClass, SUCCESSION__MIN_VAL);
    createEAttribute(successionEClass, SUCCESSION__MAX_VAL);

    coExistanceEClass = createEClass(CO_EXISTANCE);
    createEReference(coExistanceEClass, CO_EXISTANCE__REF_A);

    respondedExistenceEClass = createEClass(RESPONDED_EXISTENCE);
    createEAttribute(respondedExistenceEClass, RESPONDED_EXISTENCE__EITHER_A);
    createEReference(respondedExistenceEClass, RESPONDED_EXISTENCE__REF_A);
    createEAttribute(respondedExistenceEClass, RESPONDED_EXISTENCE__EITHER_B);
    createEReference(respondedExistenceEClass, RESPONDED_EXISTENCE__REF_B);

    chainPrecedenceEClass = createEClass(CHAIN_PRECEDENCE);
    createEAttribute(chainPrecedenceEClass, CHAIN_PRECEDENCE__EITHER_B);
    createEReference(chainPrecedenceEClass, CHAIN_PRECEDENCE__REF_B);
    createEAttribute(chainPrecedenceEClass, CHAIN_PRECEDENCE__EITHER_A);
    createEReference(chainPrecedenceEClass, CHAIN_PRECEDENCE__REF_A);
    createEAttribute(chainPrecedenceEClass, CHAIN_PRECEDENCE__NOT);
    createEAttribute(chainPrecedenceEClass, CHAIN_PRECEDENCE__MIN_VAL);
    createEAttribute(chainPrecedenceEClass, CHAIN_PRECEDENCE__MAX_VAL);

    chainResponseEClass = createEClass(CHAIN_RESPONSE);
    createEAttribute(chainResponseEClass, CHAIN_RESPONSE__EITHER_A);
    createEReference(chainResponseEClass, CHAIN_RESPONSE__REF_A);
    createEAttribute(chainResponseEClass, CHAIN_RESPONSE__EITHER_B);
    createEReference(chainResponseEClass, CHAIN_RESPONSE__REF_B);
    createEAttribute(chainResponseEClass, CHAIN_RESPONSE__NOT);
    createEAttribute(chainResponseEClass, CHAIN_RESPONSE__MIN_VAL);
    createEAttribute(chainResponseEClass, CHAIN_RESPONSE__MAX_VAL);

    alternateResponseEClass = createEClass(ALTERNATE_RESPONSE);
    createEAttribute(alternateResponseEClass, ALTERNATE_RESPONSE__EITHER_A);
    createEReference(alternateResponseEClass, ALTERNATE_RESPONSE__REF_A);
    createEAttribute(alternateResponseEClass, ALTERNATE_RESPONSE__EITHER_B);
    createEReference(alternateResponseEClass, ALTERNATE_RESPONSE__REF_B);
    createEAttribute(alternateResponseEClass, ALTERNATE_RESPONSE__MIN_VAL);
    createEAttribute(alternateResponseEClass, ALTERNATE_RESPONSE__MAX_VAL);
    createEAttribute(alternateResponseEClass, ALTERNATE_RESPONSE__NOT);
    createEAttribute(alternateResponseEClass, ALTERNATE_RESPONSE__EITHER_C);
    createEReference(alternateResponseEClass, ALTERNATE_RESPONSE__REF_C);

    alternatePrecedenceEClass = createEClass(ALTERNATE_PRECEDENCE);
    createEAttribute(alternatePrecedenceEClass, ALTERNATE_PRECEDENCE__EITHER_B);
    createEReference(alternatePrecedenceEClass, ALTERNATE_PRECEDENCE__REF_B);
    createEAttribute(alternatePrecedenceEClass, ALTERNATE_PRECEDENCE__EITHER_A);
    createEReference(alternatePrecedenceEClass, ALTERNATE_PRECEDENCE__REF_A);
    createEAttribute(alternatePrecedenceEClass, ALTERNATE_PRECEDENCE__MIN_VAL);
    createEAttribute(alternatePrecedenceEClass, ALTERNATE_PRECEDENCE__MAX_VAL);
    createEAttribute(alternatePrecedenceEClass, ALTERNATE_PRECEDENCE__NOT);
    createEAttribute(alternatePrecedenceEClass, ALTERNATE_PRECEDENCE__EITHER_C);
    createEReference(alternatePrecedenceEClass, ALTERNATE_PRECEDENCE__REF_C);

    responseEClass = createEClass(RESPONSE);
    createEAttribute(responseEClass, RESPONSE__EITHER_A);
    createEReference(responseEClass, RESPONSE__REF_A);
    createEAttribute(responseEClass, RESPONSE__EITHER_B);
    createEReference(responseEClass, RESPONSE__REF_B);
    createEAttribute(responseEClass, RESPONSE__NOT);
    createEAttribute(responseEClass, RESPONSE__MIN_VAL);
    createEAttribute(responseEClass, RESPONSE__MAX_VAL);

    precedenceEClass = createEClass(PRECEDENCE);
    createEAttribute(precedenceEClass, PRECEDENCE__EITHER_B);
    createEReference(precedenceEClass, PRECEDENCE__REF_B);
    createEAttribute(precedenceEClass, PRECEDENCE__EITHER_A);
    createEReference(precedenceEClass, PRECEDENCE__REF_A);
    createEAttribute(precedenceEClass, PRECEDENCE__NOT);
    createEAttribute(precedenceEClass, PRECEDENCE__MIN_VAL);
    createEAttribute(precedenceEClass, PRECEDENCE__MAX_VAL);

    endEClass = createEClass(END);
    createEReference(endEClass, END__REF);

    initEClass = createEClass(INIT);
    createEReference(initEClass, INIT__REF);

    atMostEClass = createEClass(AT_MOST);
    createEReference(atMostEClass, AT_MOST__REF);
    createEAttribute(atMostEClass, AT_MOST__NUM);

    exactEClass = createEClass(EXACT);
    createEReference(exactEClass, EXACT__REF);
    createEAttribute(exactEClass, EXACT__NUM);
    createEAttribute(exactEClass, EXACT__CONSECUTIVELY);
    createEAttribute(exactEClass, EXACT__MIN_VAL);
    createEAttribute(exactEClass, EXACT__MAX_VAL);

    atLeastEClass = createEClass(AT_LEAST);
    createEReference(atLeastEClass, AT_LEAST__REF);
    createEAttribute(atLeastEClass, AT_LEAST__NUM);
    createEAttribute(atLeastEClass, AT_LEAST__MIN_VAL);
    createEAttribute(atLeastEClass, AT_LEAST__MAX_VAL);

    // Create enums
    actionTypeEEnum = createEEnum(ACTION_TYPE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Obtain other dependent packages
    ExpressionsPackage theExpressionsPackage = (ExpressionsPackage)EPackage.Registry.INSTANCE.getEPackage(ExpressionsPackage.eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    refStepEClass.getESuperTypes().add(this.getRef());
    refSequenceEClass.getESuperTypes().add(this.getRef());

    // Initialize classes and features; add operations and parameters
    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModel_Features(), this.getFeatures(), null, "features", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModel_Actions(), this.getActions(), null, "actions", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModel_Sequences(), this.getSequenceDef(), null, "sequences", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModel_Composition(), this.getComposition(), null, "composition", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModel_CommonFeatures(), this.getFeature(), null, "commonFeatures", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModel_Templates(), this.getTemplates(), null, "templates", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getModel_UseLabels(), ecorePackage.getEBoolean(), "useLabels", null, 0, 1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(compositionEClass, Composition.class, "Composition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getComposition_Name(), ecorePackage.getEString(), "name", null, 0, 1, Composition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComposition_Templates(), this.getTemplates(), null, "templates", null, 0, -1, Composition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getComposition_DescTxt(), ecorePackage.getEString(), "descTxt", null, 0, 1, Composition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComposition_CommonFeatures(), this.getFeature(), null, "commonFeatures", null, 0, -1, Composition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getComposition_TagStr(), ecorePackage.getEString(), "tagStr", null, 0, -1, Composition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(sequenceDefEClass, SequenceDef.class, "SequenceDef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSequenceDef_Name(), ecorePackage.getEString(), "name", null, 0, 1, SequenceDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSequenceDef_ActList(), this.getParamAct(), null, "actList", null, 0, -1, SequenceDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(paramActEClass, ParamAct.class, "ParamAct", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getParamAct_Act(), this.getAction(), null, "act", null, 0, 1, ParamAct.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getParamAct_Idx(), ecorePackage.getEInt(), "idx", null, 0, 1, ParamAct.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(refEClass, Ref.class, "Ref", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(refStepEClass, RefStep.class, "RefStep", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getRefStep_Step(), this.getAction(), null, "step", null, 0, 1, RefStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRefStep_Idx(), ecorePackage.getEInt(), "idx", null, 0, 1, RefStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(refSequenceEClass, RefSequence.class, "RefSequence", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getRefSequence_Seq(), this.getSequenceDef(), null, "seq", null, 0, 1, RefSequence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(featuresEClass, Features.class, "Features", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getFeatures_Feature(), this.getFeature(), null, "feature", null, 0, -1, Features.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(featureEClass, Feature.class, "Feature", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFeature_Name(), ecorePackage.getEString(), "name", null, 0, 1, Feature.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(actionsEClass, Actions.class, "Actions", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getActions_Act(), this.getAction(), null, "act", null, 0, -1, Actions.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(actionParamEClass, ActionParam.class, "ActionParam", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getActionParam_Parameters(), theExpressionsPackage.getExpression(), null, "parameters", null, 0, -1, ActionParam.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(actionEClass, Action.class, "Action", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAction_Act(), this.getActionType(), "act", null, 0, 1, Action.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAction_Name(), ecorePackage.getEString(), "name", null, 0, 1, Action.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAction_Label(), ecorePackage.getEString(), "label", null, 0, 1, Action.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAction_ActParam(), this.getActionParam(), null, "actParam", null, 0, -1, Action.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(templatesEClass, Templates.class, "Templates", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTemplates_Name(), ecorePackage.getEString(), "name", null, 0, 1, Templates.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTemplates_Type(), ecorePackage.getEObject(), null, "type", null, 0, -1, Templates.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTemplates_Features(), this.getFeature(), null, "features", null, 0, -1, Templates.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(pastEClass, Past.class, "Past", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPast_Type(), ecorePackage.getEObject(), null, "type", null, 0, -1, Past.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(futureEClass, Future.class, "Future", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getFuture_Type(), ecorePackage.getEObject(), null, "type", null, 0, -1, Future.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dependenciesEClass, Dependencies.class, "Dependencies", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDependencies_Type(), ecorePackage.getEObject(), null, "type", null, 0, -1, Dependencies.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(choiceEClass, Choice.class, "Choice", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getChoice_Type(), ecorePackage.getEObject(), null, "type", null, 0, -1, Choice.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(existentialEClass, Existential.class, "Existential", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExistential_Type(), ecorePackage.getEObject(), null, "type", null, 0, -1, Existential.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(exclusiveChoiceEClass, ExclusiveChoice.class, "ExclusiveChoice", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getExclusiveChoice_EitherA(), ecorePackage.getEBoolean(), "eitherA", null, 0, 1, ExclusiveChoice.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getExclusiveChoice_RefA(), this.getRef(), null, "refA", null, 0, -1, ExclusiveChoice.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getExclusiveChoice_EitherB(), ecorePackage.getEBoolean(), "eitherB", null, 0, 1, ExclusiveChoice.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getExclusiveChoice_RefB(), this.getRef(), null, "refB", null, 0, -1, ExclusiveChoice.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(simpleChoiceEClass, SimpleChoice.class, "SimpleChoice", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSimpleChoice_RefA(), this.getRef(), null, "refA", null, 0, -1, SimpleChoice.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(notChainSuccessionEClass, NotChainSuccession.class, "NotChainSuccession", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getNotChainSuccession_EitherA(), ecorePackage.getEBoolean(), "eitherA", null, 0, 1, NotChainSuccession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getNotChainSuccession_RefA(), this.getRef(), null, "refA", null, 0, -1, NotChainSuccession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getNotChainSuccession_EitherB(), ecorePackage.getEBoolean(), "eitherB", null, 0, 1, NotChainSuccession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getNotChainSuccession_RefB(), this.getRef(), null, "refB", null, 0, -1, NotChainSuccession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(notCoExistanceEClass, NotCoExistance.class, "NotCoExistance", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getNotCoExistance_RefA(), this.getRef(), null, "refA", null, 0, -1, NotCoExistance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(notSuccessionEClass, NotSuccession.class, "NotSuccession", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getNotSuccession_EitherA(), ecorePackage.getEBoolean(), "eitherA", null, 0, 1, NotSuccession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getNotSuccession_RefA(), this.getRef(), null, "refA", null, 0, -1, NotSuccession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getNotSuccession_EitherB(), ecorePackage.getEBoolean(), "eitherB", null, 0, 1, NotSuccession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getNotSuccession_RefB(), this.getRef(), null, "refB", null, 0, -1, NotSuccession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(chainSuccessionEClass, ChainSuccession.class, "ChainSuccession", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getChainSuccession_EitherA(), ecorePackage.getEBoolean(), "eitherA", null, 0, 1, ChainSuccession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getChainSuccession_RefA(), this.getRef(), null, "refA", null, 0, -1, ChainSuccession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getChainSuccession_EitherB(), ecorePackage.getEBoolean(), "eitherB", null, 0, 1, ChainSuccession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getChainSuccession_RefB(), this.getRef(), null, "refB", null, 0, -1, ChainSuccession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getChainSuccession_MinVal(), ecorePackage.getEInt(), "minVal", null, 0, 1, ChainSuccession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getChainSuccession_MaxVal(), ecorePackage.getEInt(), "maxVal", null, 0, 1, ChainSuccession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(alternateSuccessionEClass, AlternateSuccession.class, "AlternateSuccession", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAlternateSuccession_EitherA(), ecorePackage.getEBoolean(), "eitherA", null, 0, 1, AlternateSuccession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAlternateSuccession_RefA(), this.getRef(), null, "refA", null, 0, -1, AlternateSuccession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAlternateSuccession_EitherB(), ecorePackage.getEBoolean(), "eitherB", null, 0, 1, AlternateSuccession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAlternateSuccession_RefB(), this.getRef(), null, "refB", null, 0, -1, AlternateSuccession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAlternateSuccession_EitherC(), ecorePackage.getEBoolean(), "eitherC", null, 0, 1, AlternateSuccession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAlternateSuccession_Negation(), ecorePackage.getEBoolean(), "negation", null, 0, 1, AlternateSuccession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAlternateSuccession_RefC(), this.getRef(), null, "refC", null, 0, -1, AlternateSuccession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(successionEClass, Succession.class, "Succession", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSuccession_EitherA(), ecorePackage.getEBoolean(), "eitherA", null, 0, 1, Succession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSuccession_RefA(), this.getRef(), null, "refA", null, 0, -1, Succession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSuccession_EitherB(), ecorePackage.getEBoolean(), "eitherB", null, 0, 1, Succession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSuccession_RefB(), this.getRef(), null, "refB", null, 0, -1, Succession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSuccession_MinVal(), ecorePackage.getEInt(), "minVal", null, 0, 1, Succession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSuccession_MaxVal(), ecorePackage.getEInt(), "maxVal", null, 0, 1, Succession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(coExistanceEClass, CoExistance.class, "CoExistance", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCoExistance_RefA(), this.getRef(), null, "refA", null, 0, -1, CoExistance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(respondedExistenceEClass, RespondedExistence.class, "RespondedExistence", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRespondedExistence_EitherA(), ecorePackage.getEBoolean(), "eitherA", null, 0, 1, RespondedExistence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRespondedExistence_RefA(), this.getRef(), null, "refA", null, 0, -1, RespondedExistence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRespondedExistence_EitherB(), ecorePackage.getEBoolean(), "eitherB", null, 0, 1, RespondedExistence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRespondedExistence_RefB(), this.getRef(), null, "refB", null, 0, -1, RespondedExistence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(chainPrecedenceEClass, ChainPrecedence.class, "ChainPrecedence", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getChainPrecedence_EitherB(), ecorePackage.getEBoolean(), "eitherB", null, 0, 1, ChainPrecedence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getChainPrecedence_RefB(), this.getRef(), null, "refB", null, 0, -1, ChainPrecedence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getChainPrecedence_EitherA(), ecorePackage.getEBoolean(), "eitherA", null, 0, 1, ChainPrecedence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getChainPrecedence_RefA(), this.getRef(), null, "refA", null, 0, -1, ChainPrecedence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getChainPrecedence_Not(), ecorePackage.getEBoolean(), "not", null, 0, 1, ChainPrecedence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getChainPrecedence_MinVal(), ecorePackage.getEInt(), "minVal", null, 0, 1, ChainPrecedence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getChainPrecedence_MaxVal(), ecorePackage.getEInt(), "maxVal", null, 0, 1, ChainPrecedence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(chainResponseEClass, ChainResponse.class, "ChainResponse", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getChainResponse_EitherA(), ecorePackage.getEBoolean(), "eitherA", null, 0, 1, ChainResponse.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getChainResponse_RefA(), this.getRef(), null, "refA", null, 0, -1, ChainResponse.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getChainResponse_EitherB(), ecorePackage.getEBoolean(), "eitherB", null, 0, 1, ChainResponse.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getChainResponse_RefB(), this.getRef(), null, "refB", null, 0, -1, ChainResponse.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getChainResponse_Not(), ecorePackage.getEBoolean(), "not", null, 0, 1, ChainResponse.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getChainResponse_MinVal(), ecorePackage.getEInt(), "minVal", null, 0, 1, ChainResponse.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getChainResponse_MaxVal(), ecorePackage.getEInt(), "maxVal", null, 0, 1, ChainResponse.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(alternateResponseEClass, AlternateResponse.class, "AlternateResponse", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAlternateResponse_EitherA(), ecorePackage.getEBoolean(), "eitherA", null, 0, 1, AlternateResponse.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAlternateResponse_RefA(), this.getRef(), null, "refA", null, 0, -1, AlternateResponse.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAlternateResponse_EitherB(), ecorePackage.getEBoolean(), "eitherB", null, 0, 1, AlternateResponse.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAlternateResponse_RefB(), this.getRef(), null, "refB", null, 0, -1, AlternateResponse.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAlternateResponse_MinVal(), ecorePackage.getEInt(), "minVal", null, 0, 1, AlternateResponse.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAlternateResponse_MaxVal(), ecorePackage.getEInt(), "maxVal", null, 0, 1, AlternateResponse.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAlternateResponse_Not(), ecorePackage.getEBoolean(), "not", null, 0, 1, AlternateResponse.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAlternateResponse_EitherC(), ecorePackage.getEBoolean(), "eitherC", null, 0, 1, AlternateResponse.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAlternateResponse_RefC(), this.getRef(), null, "refC", null, 0, -1, AlternateResponse.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(alternatePrecedenceEClass, AlternatePrecedence.class, "AlternatePrecedence", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAlternatePrecedence_EitherB(), ecorePackage.getEBoolean(), "eitherB", null, 0, 1, AlternatePrecedence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAlternatePrecedence_RefB(), this.getRef(), null, "refB", null, 0, -1, AlternatePrecedence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAlternatePrecedence_EitherA(), ecorePackage.getEBoolean(), "eitherA", null, 0, 1, AlternatePrecedence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAlternatePrecedence_RefA(), this.getRef(), null, "refA", null, 0, -1, AlternatePrecedence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAlternatePrecedence_MinVal(), ecorePackage.getEInt(), "minVal", null, 0, 1, AlternatePrecedence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAlternatePrecedence_MaxVal(), ecorePackage.getEInt(), "maxVal", null, 0, 1, AlternatePrecedence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAlternatePrecedence_Not(), ecorePackage.getEBoolean(), "not", null, 0, 1, AlternatePrecedence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAlternatePrecedence_EitherC(), ecorePackage.getEBoolean(), "eitherC", null, 0, 1, AlternatePrecedence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAlternatePrecedence_RefC(), this.getRef(), null, "refC", null, 0, -1, AlternatePrecedence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(responseEClass, Response.class, "Response", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getResponse_EitherA(), ecorePackage.getEBoolean(), "eitherA", null, 0, 1, Response.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getResponse_RefA(), this.getRef(), null, "refA", null, 0, -1, Response.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getResponse_EitherB(), ecorePackage.getEBoolean(), "eitherB", null, 0, 1, Response.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getResponse_RefB(), this.getRef(), null, "refB", null, 0, -1, Response.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getResponse_Not(), ecorePackage.getEBoolean(), "not", null, 0, 1, Response.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getResponse_MinVal(), ecorePackage.getEInt(), "minVal", null, 0, 1, Response.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getResponse_MaxVal(), ecorePackage.getEInt(), "maxVal", null, 0, 1, Response.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(precedenceEClass, Precedence.class, "Precedence", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPrecedence_EitherB(), ecorePackage.getEBoolean(), "eitherB", null, 0, 1, Precedence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPrecedence_RefB(), this.getRef(), null, "refB", null, 0, -1, Precedence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPrecedence_EitherA(), ecorePackage.getEBoolean(), "eitherA", null, 0, 1, Precedence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPrecedence_RefA(), this.getRef(), null, "refA", null, 0, -1, Precedence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPrecedence_Not(), ecorePackage.getEBoolean(), "not", null, 0, 1, Precedence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPrecedence_MinVal(), ecorePackage.getEInt(), "minVal", null, 0, 1, Precedence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPrecedence_MaxVal(), ecorePackage.getEInt(), "maxVal", null, 0, 1, Precedence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(endEClass, End.class, "End", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEnd_Ref(), this.getRef(), null, "ref", null, 0, -1, End.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(initEClass, Init.class, "Init", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getInit_Ref(), this.getRef(), null, "ref", null, 0, -1, Init.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(atMostEClass, AtMost.class, "AtMost", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAtMost_Ref(), this.getRef(), null, "ref", null, 0, -1, AtMost.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAtMost_Num(), ecorePackage.getEInt(), "num", null, 0, 1, AtMost.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(exactEClass, Exact.class, "Exact", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExact_Ref(), this.getRef(), null, "ref", null, 0, -1, Exact.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getExact_Num(), ecorePackage.getEInt(), "num", null, 0, 1, Exact.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getExact_Consecutively(), ecorePackage.getEBoolean(), "consecutively", null, 0, 1, Exact.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getExact_MinVal(), ecorePackage.getEInt(), "minVal", null, 0, 1, Exact.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getExact_MaxVal(), ecorePackage.getEInt(), "maxVal", null, 0, 1, Exact.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(atLeastEClass, AtLeast.class, "AtLeast", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAtLeast_Ref(), this.getRef(), null, "ref", null, 0, -1, AtLeast.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAtLeast_Num(), ecorePackage.getEInt(), "num", null, 0, 1, AtLeast.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAtLeast_MinVal(), ecorePackage.getEInt(), "minVal", null, 0, 1, AtLeast.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAtLeast_MaxVal(), ecorePackage.getEInt(), "maxVal", null, 0, 1, AtLeast.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(actionTypeEEnum, ActionType.class, "ActionType");
    addEEnumLiteral(actionTypeEEnum, ActionType.OBSERVABLE);
    addEEnumLiteral(actionTypeEEnum, ActionType.TRIGGER);
    addEEnumLiteral(actionTypeEEnum, ActionType.PRE_CONDITION);
    addEEnumLiteral(actionTypeEEnum, ActionType.CONJUNCTION);

    // Create resource
    createResource(eNS_URI);
  }

} //SclPackageImpl
