/**
 * generated by Xtext 2.25.0
 */
package nl.esi.comma.expressions.expressions;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression Minus</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see nl.esi.comma.expressions.expressions.ExpressionsPackage#getExpressionMinus()
 * @model
 * @generated
 */
public interface ExpressionMinus extends Expression, ExpressionUnary
{
} // ExpressionMinus
