/*
 * generated by Xtext 2.25.0
 */
package nl.esi.comma.behavior.scl.ui.tests;

import com.google.inject.Injector;
import nl.esi.comma.behavior.scl.ui.internal.SclActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class SclUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SclActivator.getInstance().getInjector("nl.esi.comma.behavior.scl.Scl");
	}

}
