/*
 * generated by Xtext 2.25.0
 */
package nl.esi.comma.behavior.scl.validation;

import java.util.ArrayList;
import java.util.List;
import nl.esi.comma.expressions.validation.ExpressionsValidator;
import org.eclipse.emf.ecore.EPackage;

public abstract class AbstractSclValidator extends ExpressionsValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>(super.getEPackages());
		result.add(nl.esi.comma.behavior.scl.scl.SclPackage.eINSTANCE);
		return result;
	}
}
