/*
 * generated by Xtext 2.25.0
 */
package nl.esi.comma.expressions.ui.tests;

import com.google.inject.Injector;
import nl.esi.comma.expressions.ui.internal.ExpressionsActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ExpressionsUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ExpressionsActivator.getInstance().getInjector("nl.esi.comma.expressions.Expressions");
	}

}
