/*
 * generated by Xtext 2.25.0
 */
package nl.esi.comma.expressions.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractExpressionsScopeProvider extends DelegatingScopeProvider {
}
