/*
 * generated by Xtext 2.25.0
 */
package nl.esi.comma.behavior.scl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SclRuntimeModule extends AbstractSclRuntimeModule {
}
