/*
 * generated by Xtext 2.25.0
 */
package nl.esi.comma.expressions.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractExpressionsValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(nl.esi.comma.expressions.expressions.ExpressionsPackage.eINSTANCE);
		return result;
	}
}
